
server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/sentinel_db
spring.datasource.username=sentinel
spring.datasource.password=sentinel_pass
spring.jpa.hibernate.ddl-auto=update


spring.kafka.bootstrap-servers=localhost:9092

spring.ai.openai.api-key=your_api_key_here


spring.graphql.graphiql.enabled=true